name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: dev:latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    # - name: Install Ansible
    #   run: sudo apt-get update && sudo apt-get install -y ansible
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.LIXIANGYU }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 700 ~/.ssh/ && chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 10.0.0.111 >> ~/.ssh/known_hosts
    - name: Run Ansible playbook
      run: ansible -i 10.0.0.111, all -m ping
    - name: run ansible 
      run: ansible -i 10.0.0.111, all -m shell -a "cd /root/code/zxl/word_template_plugin && git pull"
    - name: run ansible
      run: ansible -i 10.0.0.111, all -m shell -a "systemctl restart deal"
    - name: check port
      run:  echo "HTTP $(curl --write-out '%{http_code}' --silent --output /dev/null http://10.0.0.111:5001/test)"


